//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.08 at 02:20:44 PM EEST 
//


package com.msdp.kone.m2m.client;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.msdp.kone.m2m.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.msdp.kone.m2m.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Identifiers }
     * 
     */
    public Identifiers createIdentifiers() {
        return new Identifiers();
    }

    /**
     * Create an instance of {@link SourceIdentifiersType }
     * 
     */
    public SourceIdentifiersType createSourceIdentifiersType() {
        return new SourceIdentifiersType();
    }

    /**
     * Create an instance of {@link PayloadType }
     * 
     */
    public PayloadType createPayloadType() {
        return new PayloadType();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link Identifiers.ExtIds }
     * 
     */
    public Identifiers.ExtIds createIdentifiersExtIds() {
        return new Identifiers.ExtIds();
    }

    /**
     * Create an instance of {@link SourceIdentifiersType.ResourceSets }
     * 
     */
    public SourceIdentifiersType.ResourceSets createSourceIdentifiersTypeResourceSets() {
        return new SourceIdentifiersType.ResourceSets();
    }

    /**
     * Create an instance of {@link PayloadType.Value }
     * 
     */
    public PayloadType.Value createPayloadTypeValue() {
        return new PayloadType.Value();
    }

}
