//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.08 at 02:20:44 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:com:ericsson:schema:xml:m2m:protocols:vnd.ericsson.m2m.output", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.msdp.kone.m2m.client;
