//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.08 at 02:20:44 PM EEST 
//


package com.msdp.kone.m2m.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for payloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="payloadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="sourceIdentifiers" type="{urn:com:ericsson:schema:xml:m2m:protocols:vnd.ericsson.m2m.output}sourceIdentifiersType" minOccurs="0"/>
 *         &lt;element name="value">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:com:ericsson:schema:xml:m2m:protocols:vnd.ericsson.m2m.output>payloadValueType">
 *                 &lt;attribute name="type" type="{urn:com:ericsson:schema:xml:m2m:protocols:vnd.ericsson.m2m.output}payloadValueTypeName" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="metadata" type="{urn:com:ericsson:schema:xml:m2m:protocols:vnd.ericsson.m2m.output}metadataType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "payloadType", propOrder = {

})
public class PayloadType {

    protected SourceIdentifiersType sourceIdentifiers;
    @XmlElement(required = true)
    protected PayloadType.Value value;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    protected MetadataType metadata;

    /**
     * Gets the value of the sourceIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link SourceIdentifiersType }
     *     
     */
    public SourceIdentifiersType getSourceIdentifiers() {
        return sourceIdentifiers;
    }

    /**
     * Sets the value of the sourceIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceIdentifiersType }
     *     
     */
    public void setSourceIdentifiers(SourceIdentifiersType value) {
        this.sourceIdentifiers = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link PayloadType.Value }
     *     
     */
    public PayloadType.Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayloadType.Value }
     *     
     */
    public void setValue(PayloadType.Value value) {
        this.value = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataType }
     *     
     */
    public MetadataType getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataType }
     *     
     */
    public void setMetadata(MetadataType value) {
        this.metadata = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:com:ericsson:schema:xml:m2m:protocols:vnd.ericsson.m2m.output>payloadValueType">
     *       &lt;attribute name="type" type="{urn:com:ericsson:schema:xml:m2m:protocols:vnd.ericsson.m2m.output}payloadValueTypeName" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Value {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "type")
        protected PayloadValueTypeName type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link PayloadValueTypeName }
         *     
         */
        public PayloadValueTypeName getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link PayloadValueTypeName }
         *     
         */
        public void setType(PayloadValueTypeName value) {
            this.type = value;
        }

    }

}
